# Generated by Django 6.1.1 on 2026-09-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customer_lead_activity_opportunity_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
