# Generated by Django 6.1.1 on 2026-09-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_active_alter_user_email_alter_user_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("recipient_emails", models.TextField()),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("is_bulk", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("Failed", "Failed")],
                        default="Sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
